# Site settings
baseURL = "https://serum-n5p6.onrender.com/"
languageCode = "en-US"
title = "Serum.cloud - A Serum Node"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Serum.cloud"

[params]

  # Metadata for search engines and social sharing
  author = "Jenny Jones"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/serum-banner.png"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect to Serum"

      [[params.links.list1.link]]
        text = "Serum DEX"
        url = "https://dex.projectserum.com/"

      [[params.links.list1.link]]
        text = "Web"
        url = "https://www.projectserum.com/"

      [[params.links.list1.link]]
        text = "Sollet Wallet"
        url = "https://www.sollet.io/"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Socialize with Serum"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/projectserum"

      [[params.links.list2.link]]
        text = "Telegram"
        url = "https://t.me/ProjectSerum"

      [[params.links.list2.link]]
        text = "FTX"
        url = "https://ftx.com/#a=2929887"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Serum.could Network"

      [[params.links.list3.link]]
        text = "Mirror Dex"
        url = "#"

      [[params.links.list3.link]]
        text = "Dark Serum Node"
        url = "#"

  

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
